spring.application.name=URLino
server.port=8080
#spring.cloud.gcp.bigtable.emulator-host=localhost:8086
#spring.cloud.gcp.bigtable.project-id=test-project
#spring.cloud.gcp.bigtable.instance-id=test-instance
#spring.cloud.gcp.credentials.location=file:/dev/null
#spring.autoconfigure.exclude=com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration